version: "3.8"
services:
  app1:
    image: "nginx"
    volumes:
      - ./app1:/usr/share/nginx/html
  app2:
    image: "nginx"
    volumes:
      - ./app2:/usr/share/nginx/html
  haproxy:
    build: haproxy/
    ports:
      - "8080:80"