version: "3.8"
services:
  default-app:
    build: app/
    image: simple-web-app
  ssl-termination-1:
    image: simple-web-app
  ssl-termination-2:
    image: simple-web-app
  # app2:
  #   image: simple-web-app
  # app22:
  #   image: simple-web-app
  lb-haproxy:
    build: haproxy/
    ports:
      - "8080:80"
      - "8443:443"